Repository prafullmaru/ePanchayat, pull requests merged in 2024-06, with the labels that each got.

#3 DB Connectivity established
  ePanchayat.API/CommonUtils/Constants.cs
  ePanchayat.API/CommonUtils/SqlDataAccess.cs
  ePanchayat.API/Controllers/PanchayatController.cs
  ePanchayat.API/Interfaces/IPanchayatRepository.cs
  ePanchayat.API/Interfaces/ISqlDataAccess.cs
  ePanchayat.API/Models/Panchayat.cs
  ePanchayat.API/Program.cs
  ePanchayat.API/Repository/PanchayatRepository.cs
  ePanchayat.API/Repository/ServiceExtensions.cs
  ePanchayat.API/ePanchayat.API.csproj
Labels: initial setup

#4 Added database schema
  ePanchayat.DB/Misc/ePanchayat_CREATE_DB.sql
  ePanchayat.DB/StoredProcedures/PanchayatDelete_sp.sql
  ePanchayat.DB/StoredProcedures/PanchayatGet_sp.sql
  ePanchayat.DB/StoredProcedures/PanchayatSave_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleAccessGet_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleAccessSave_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleGet_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleSave_sp.sql
  ePanchayat.DB/StoredProcedures/UserSave_sp.sql
  ePanchayat.DB/StoredProcedures/UsersGet_sp.sql
  ePanchayat.DB/Tables/DDL/Announcement_tbl.sql
  ePanchayat.DB/Tables/DDL/Complaint_tbl.sql
  ePanchayat.DB/Tables/DDL/Event_tbl.sql
  ePanchayat.DB/Tables/DDL/House_tbl.sql
  ePanchayat.DB/Tables/DDL/Ledger_tbl.sql
  ePanchayat.DB/Tables/DDL/Panchayat_tbl.sql
  ePanchayat.DB/Tables/DDL/Qualification_tbl.sql
  ePanchayat.DB/Tables/DDL/UserRoleAccess_tbl.sql
  ePanchayat.DB/Tables/DDL/UserRole_tbl.sql
  ePanchayat.DB/Tables/DDL/User_tbl.sql
  ePanchayat.DB/Tables/DDL/Vehicle_tbl.sql
Labels: initial setup

#7 Added database schema
  ePanchayat.DB/Misc/ePanchayat_CREATE_DB.sql
  ePanchayat.DB/StoredProcedures/PanchayatDelete_sp.sql
  ePanchayat.DB/StoredProcedures/PanchayatGet_sp.sql
  ePanchayat.DB/StoredProcedures/PanchayatSave_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleAccessGet_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleAccessSave_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleGet_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleSave_sp.sql
  ePanchayat.DB/StoredProcedures/UserSave_sp.sql
  ePanchayat.DB/StoredProcedures/UsersGet_sp.sql
  ePanchayat.DB/Tables/DDL/Announcement_tbl.sql
  ePanchayat.DB/Tables/DDL/Complaint_tbl.sql
  ePanchayat.DB/Tables/DDL/Event_tbl.sql
  ePanchayat.DB/Tables/DDL/House_tbl.sql
  ePanchayat.DB/Tables/DDL/Ledger_tbl.sql
  ePanchayat.DB/Tables/DDL/Panchayat_tbl.sql
  ePanchayat.DB/Tables/DDL/Qualification_tbl.sql
  ePanchayat.DB/Tables/DDL/UserRoleAccess_tbl.sql
  ePanchayat.DB/Tables/DDL/UserRole_tbl.sql
  ePanchayat.DB/Tables/DDL/User_tbl.sql
  ePanchayat.DB/Tables/DDL/Vehicle_tbl.sql
Labels: initial setup

#18 DB changes for user details
  LICENSE
  README.md
  ePanchayat.DB/Misc/ePanchayat_CREATE_DB.sql
  ePanchayat.DB/StoredProcedures/HouseDelete_sp.sql
  ePanchayat.DB/StoredProcedures/HouseGet_sp.sql
  ePanchayat.DB/StoredProcedures/HouseSave_sp.sql
  ePanchayat.DB/StoredProcedures/PanchayatDelete_sp.sql
  ePanchayat.DB/StoredProcedures/PanchayatGet_sp.sql
  ePanchayat.DB/StoredProcedures/PanchayatSave_sp.sql
  ePanchayat.DB/StoredProcedures/QualificationDelete_sp.sql
  ePanchayat.DB/StoredProcedures/QualificationGet_sp.sql
  ePanchayat.DB/StoredProcedures/QualificationSave_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleAccessGet_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleAccessSave_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleGet_sp.sql
  ePanchayat.DB/StoredProcedures/UserRoleSave_sp.sql
  ePanchayat.DB/StoredProcedures/UserSave_sp.sql
  ePanchayat.DB/StoredProcedures/UsersGet_sp.sql
  ePanchayat.DB/StoredProcedures/VehicleDelete_sp.sql
  ePanchayat.DB/StoredProcedures/VehicleGet_sp.sql
  ePanchayat.DB/StoredProcedures/VehicleSave_sp.sql
  ePanchayat.DB/Tables/DDL/Announcement_tbl.sql
  ePanchayat.DB/Tables/DDL/Complaint_tbl.sql
  ePanchayat.DB/Tables/DDL/Event_tbl.sql
  ePanchayat.DB/Tables/DDL/House_tbl.sql
  ePanchayat.DB/Tables/DDL/Ledger_tbl.sql
  ePanchayat.DB/Tables/DDL/Panchayat_tbl.sql
  ePanchayat.DB/Tables/DDL/Qualification_tbl.sql
  ePanchayat.DB/Tables/DDL/UserRoleAccess_tbl.sql
  ePanchayat.DB/Tables/DDL/UserRole_tbl.sql
  ePanchayat.DB/Tables/DDL/User_tbl.sql
  ePanchayat.DB/Tables/DDL/Vehicle_tbl.sql
Labels: feature

#27 Included carousel images and updates dashboard
  ePanchayat.Web/src/core/styles/scss/carousel.scss
  ePanchayat.Web/src/dashboard/dashbaord-carousel.component.html
  ePanchayat.Web/src/dashboard/dashboard.component.scss
  ePanchayat.Web/src/favicon.ico
Labels: help wanted

#31 Updated all menu navigation
  ePanchayat.Web/src/core/services/navigation-data/navigation-data.service.ts
  ePanchayat.Web/src/module-container/module-container.component.ts
  ePanchayat.Web/src/routes/admin-route.module.ts
  ePanchayat.Web/src/routes/analytics-route.module.ts
  ePanchayat.Web/src/routes/complaint-route.module.ts
  ePanchayat.Web/src/routes/events-route.module.ts
  ePanchayat.Web/src/routes/finance-route.module.ts
  ePanchayat.Web/src/routes/gallery-route.module.ts
Labels: enhancement
